version: "3.9"
services:
  server:
    build: ./server/.
    links:
      - db
  client:
    build: ./client/.
    ports:
      - 3000:3000
    links:
      - server
  db:
    image: "postgres:alpine"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=TechShop
volumes:
  pgdata:
